networks:
  barter-system:


services:
  # сервис основного приложения
  barter--app:
    build: .
    image: barter-system
    container_name: barter-app
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./logs:/logs
      - ./docs:/docs
    working_dir: /src/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - barter-system
    links:
      - barter-db
    depends_on:
      - barter-db

  # база данных
  barter-db:
    image: postgres:15-alpine
    container_name: barter-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_sample:/var/lib/postgresql/data/
    ports:
      - "55432:5432"
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
    healthcheck:
      # https://www.postgresql.org/docs/current/app-pg-isready.html
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - barter-system

volumes:
  postgres_data_sample:
